# .github/dependabot.yml
version: 2
updates:
    - package-ecosystem: npm
      directory: /
      target-branch: develop
      schedule:
          interval: monthly
          time: '14:00'
          timezone: 'Australia/Adelaide'
      groups:
          npm:
              patterns:
                  - '*'
      cooldown:
          default-days: 7
      ignore:
          - dependency-name: remark-math
            update-types:
                - version-update:semver-major
          - dependency-name: typescript
            update-types:
                - version-update:semver-major
          - dependency-name: vite
            update-types:
                - version-update:semver-major
          - dependency-name: '@sveltejs/vite-plugin-svelte'
            update-types:
                - version-update:semver-major
      reviewers:
          - santiagosayshey
      labels:
          - dependencies

    - package-ecosystem: github-actions
      directory: /
      target-branch: develop
      schedule:
          interval: weekly
          day: monday
          time: '14:00'
          timezone: 'Australia/Adelaide'
      groups:
          github:
              patterns:
                  - '*'
      cooldown:
          default-days: 7
